language: node_js
node_js:
  - "8.0"
branches:
  only:
  - master
  - staging
  - development
script:
  - npm run-script build
cache:
directories:
  - "node_modules"
install:
  - if [[ ${TRAVIS_BRANCH} == "master" ]]; then echo "tried to"; fi;
  - npm install
  - npm install -g firebase-tools
after_success:
  - if [[ ${TRAVIS_BRANCH} == "master" ]]; then
      echo "tried to";
      firebase deploy --token ${FIREBASE_TOKEN};
    else
      firebase deploy -P development --token ${FIREBASE_TOKEN}
    fi;
