language: node_js
node_js:
  - "8.0"
branches:
  only:
  - master
  - staging
  - development
script:
  - npm run-script build
  - if [[ ${TRAVIS_BRANCH} == "master" ]]; then echo "tried to"; fi;
cache:
directories:
  - "node_modules"
install:
  - npm install
  - npm install -g firebase-tools
after_success:
  - firebase deploy -P development --token ${FIREBASE_TOKEN}
