language: node_js
node_js:
  - "8.0"
  branches:
  only:
  - master
  - staging
  - development
script:
  - npm run-script build
cache:
directories:
  - "node_modules"
install:
 - npm install
 - npm install -g firebase-tools
after_success:
- 'if [ ${$TRAVIS_BRANCH} = "master" ]; then
          firebase deploy --token $FIREBASE_TOKEN

      else
          firebase deploy -P development --token $FIREBASE_TOKEN
      fi'
