language: node_js
node_js:
  - "8.0"
branches:
  only:
  - master
  - staging
  - development
script:
  - npm run-script build
cache:
directories:
  - "node_modules"
install:
  - npm install
  - npm install -g firebase-tools
after_success:
  - ./scripts/deploy_to_s3.sh