language: node_js
node_js:
  - "8.0"
branches:
  only:
  - master
  - staging
  - development
script:
  - npm run-script build
  - if [ $TRAVIS_BRANCH == "master" ]; then export FIREBASE_DEPLOY_KEY=$FIREBASE_TOKEN; else FIREBASE_DEPLOY_KEY=$FIREBASE_TOKEN_DEV; fi
  - if [ $TRAVIS_BRANCH == "master" ]; then export FIREBASE_PROJECT="default"; else export FIREBASE_PROJECT="development"; fi
  - echo $FIREBASE_PROJECT
  - firebase use $FIREBASE_PROJECT --token $FIREBASE_DEPLOY_KEY
  - export COMMIT_HASH=$(echo $TRAVIS_COMMIT | cut -b -6)
  - firebase deploy -m "build $TRAVIS_BUILD_NUMBER $TRAVIS_BRANCH/$COMMIT_HASH" --non-interactive --token $FIREBASE_DEPLOY_KEY
cache:
directories:
  - "node_modules"
install:
  - npm install
  - npm install -g firebase-tools