language: node_js
node_js:
  - "8.0"
branches:
  only:
  - master
  - staging
  - development
script:
  - npm run-script build
cache:
directories:
  - "node_modules"
install:
  - npm install
  - npm install -g firebase-tools
deploy:
  - provider: firebase
    project: "bad-news-dev"
    token:
      secure: ${FIREBASE_TOKEN}
    on:
      branch: development
  - provider: firebase
    project: "bad-news-staging"
    token:
      secure: ${FIREBASE_TOKEN}
    on:
      branch: staging
  - provider: firebase
    project: "bad-news"
    token:
      secure: ${FIREBASE_TOKEN}
    on:
      branch: master

